### ISSUE TITLE
Invalid formula

### ISSUE THREAD

**Issue by romeomanzur** [phalcon/homebrew-tap#23]
When I try to install with brew following your steps, I received the following error:

% brew tap phalcon/extension https://github.com/phalcon/homebrew-tap
==> Tapping phalcon/extension
Cloning into '/usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension'...
remote: Enumerating objects: 291, done.
remote: Counting objects: 100% (137/137), done.
remote: Compressing objects: 100% (82/82), done.
remote: Total 291 (delta 76), reused 64 (delta 41), pack-reused 154
Receiving objects: 100% (291/291), 52.54 KiB | 459.00 KiB/s, done.
Resolving deltas: 100% (160/160), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.0.0.rb
phalcon@4.0.0: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the phalcon/extension tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.0.0.rb:12

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/psr@74.rb
psr@74: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the phalcon/extension tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/psr@74.rb:12

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.0.4.rb
phalcon@4.0.4: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the phalcon/extension tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.0.4.rb:12

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@3.4.rb
phalcon@3.4: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the phalcon/extension tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@3.4.rb:12

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.0.5.rb
phalcon@4.0.5: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the phalcon/extension tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.0.5.rb:12

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.1.0.rb
phalcon@4.1.0: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the phalcon/extension tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.1.0.rb:12

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.0rc3.rb
phalcon@4.0rc3: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the phalcon/extension tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.0rc3.rb:12

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.0rc2.rb
phalcon@4.0rc2: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the phalcon/extension tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.0rc2.rb:12

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@73_4.0.0.rb
phalcon@73_4.0.0: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the phalcon/extension tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@73_4.0.0.rb:12

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.0.6.rb
phalcon@4.0.6: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the phalcon/extension tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.0.6.rb:12

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.0.2.rb
phalcon@4.0.2: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the phalcon/extension tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.0.2.rb:12

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/psr@73.rb
psr@73: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the phalcon/extension tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/psr@73.rb:12

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.0.3.rb
phalcon@4.0.3: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the phalcon/extension tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.0.3.rb:12

Error: Cannot tap phalcon/extension: invalid syntax in tap!

**Comment by logixode** [comment]
Hey, I have the same problems.
<img width="1172" alt="Screen Shot 2021-08-16 at 10 14 46" src="https://user-images.githubusercontent.com/41426110/129529436-4de703c3-a198-48c7-8040-547105fcadbf.png">

**Comment by logixode** [comment]
```
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.0.0.rb
phalcon@4.0.0: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the phalcon/extension tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.0.0.rb:12

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/psr@74.rb
psr@74: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the phalcon/extension tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/psr@74.rb:12

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.0.4.rb
phalcon@4.0.4: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the phalcon/extension tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.0.4.rb:12

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@3.4.rb
phalcon@3.4: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the phalcon/extension tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@3.4.rb:12

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.0.5.rb
phalcon@4.0.5: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the phalcon/extension tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.0.5.rb:12

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.1.0.rb
phalcon@4.1.0: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the phalcon/extension tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.1.0.rb:12

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.0rc3.rb
phalcon@4.0rc3: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the phalcon/extension tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.0rc3.rb:12

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.0rc2.rb
phalcon@4.0rc2: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the phalcon/extension tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.0rc2.rb:12

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@73_4.0.0.rb
phalcon@73_4.0.0: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the phalcon/extension tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@73_4.0.0.rb:12

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.0.6.rb
phalcon@4.0.6: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the phalcon/extension tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.0.6.rb:12

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.0.2.rb
phalcon@4.0.2: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the phalcon/extension tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.0.2.rb:12

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/psr@73.rb
psr@73: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the phalcon/extension tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/psr@73.rb:12

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.0.3.rb
phalcon@4.0.3: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the phalcon/extension tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/phalcon/homebrew-extension/Formula/phalcon@4.0.3.rb:12

Error: Cannot tap phalcon/extension: invalid syntax in tap!
```

**Comment by wreckitq** [comment]
same here

**Comment by logixode** [comment]
Dead framework

**Comment by 102er** [comment]
How to solve this problem？

**Comment by wreckitq** [comment]
still have no idea

**Comment by AlexNDRmac** [comment]
We'll fix it soon.

**Comment by KeronLewisGit** [comment]
SO, is this fixed?
