### ISSUE TITLE
Tap doesn't install under Catalina

### ISSUE THREAD

**Issue by ruudboon** [phalcon/homebrew-tap#5]
We got a report that the install fails under Catalina. (https://github.com/shivammathur/setup-php/issues/128)
I can do some debugging this week.

**Comment by ninjapanzer** [comment]
So far at least regarding a vanilla install from source on Catalina it looks good
https://pipelines.actions.githubusercontent.com/rORqz4DcgliOr7Ieb8FhcNNUEWYDYUyFHDewNwCiWvDLUBGnXt/_apis/pipelines/1/runs/8/signedlogcontent/3?urlExpires=2019-12-29T21%3A27%3A13.9929688Z&urlSigningMethod=HMACV1&urlSignature=7rD%2B2gkZ7qsMsgGo4uQpx0soRkuKGBjiLP1Gw2OL5rg%3D

**Comment by ninjapanzer** [comment]
Ok so with some fancy screwing around in github actions I can confirm that when --without-homebrew-php is used phalcon is unable to link against the php headerfiles it expects in /usr/local/... So this is either nuance of catalina or its a nuance of homebrew.

I confirmed that against the official PHP maintained by homebrew and the tap provided by @shivammathur exposes the same behavior

**Comment by ninjapanzer** [comment]
Its been concluded that the issue is not related to catalina but how `make` is able to find its php configuration during extension compilation
